[parity]
#chain = "./home/parity/.local/share/io.parity.ethereum/chain.json"
#base_path = "./home/parity/.local/share/io.parity.ethereum"
#db_path = "./home/parity/.local/share/io.parity.ethereum/chains"
#keys_path = "./home/parity/.local/share/io.parity.ethereum/keys"

[rpc]
disable = false
port = 8545
interface = "all"
cors = ["all"]
hosts = ["all"]
apis = ["web3", "eth", "net", "parity", "traces", "rpc", "personal", "parity_accounts", "signer", "parity_set"]

[network]
bootnodes = [
  "enode://147573f46fe9f5cc38fbe070089a31390baec5dd2827c8f2ef168833e4d0254fbee3969a02c5b9910ea5d5b23d86a6ed5eabcda17cc12007b7d9178b6c697aa5@172.16.0.10:30303",
]

#[account]
#password = ["./home/parity/authorities/authority.pwd"]

[mining]
engine_signer = "0x00Bd138aBD70e2F00903268F3Db08f2D25677C9e"
reseal_on_txs = "none"
reseal_min_period = 1000
reseal_max_period = 5000
gas_floor_target = "0x165A0BC00"
tx_queue_size = 16384
tx_queue_mem_limit = 4096
tx_queue_per_sender = 16384
usd_per_tx = "0"
force_sealing= true

[misc]
logging = "own_tx=trace,sync=debug,rpc=trace,mining=trace"
color = true
unsafe_expose = true

[ipc]
disable = true
